global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'aspnet-app'
    static_configs:
      - targets: ['host.docker.internal:5030', 'host.docker.internal:7216']
    metrics_path: '/metrics'
    scrape_interval: 10s
    honor_labels: true